# Site Configuration
title: Terence Schumacher
email: terenceschumacher@gmail.com
description: >-
  Software Engineer & Technical Writer. Sharing insights on development,
  algorithms, system design, and the craft of building great software.
baseurl: ""
url: "https://tazzledazzle.github.io"

# Author Information
author:
  name: Terence Schumacher
  email: terenceschumacher@gmail.com
  github: tazzledazzle
  twitter: terenceschu
  linkedin: terenceschumacher

# Social Links
github_username: tazzledazzle
twitter_username: terenceschu

gravatar_hash: 10056dfd9bd277610a657d2aee28089b

navigation:
  - { title: About, url: '/About'}
  - { title: Projects, url: '/Projects' }
  - { title: Career, url: '/Career' }
  - { title: Blog, url '/Blog' }

# Theme Configuration
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/tazzledazzle" }
    - { platform: twitter, user_url: "https://twitter.com/terenceschu" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/terenceschumacher" }

# Styling
sass:
  sass_dir: _sass
  style: compressed

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme
# remote_theme: pages-themes/time-machine@v0.2.0
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# SEO and Performance
timezone: America/Los_Angeles

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
