# Site settings
title: Terence Schumacher's Page
email: tdizzle@uw.com
description: > # this means to ignore newlines until baseurl:
  A collection of my thoughts, projects, and resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tazzledazzle.github.io"
twitter_username: terenceschu
github_username:  tazzledazzle

# Build settings
theme: minima
