(function(){
    'use strict';

    /**
     * This is the main application file.
     * Generated by ng-appgen Yeomen/Angular generator.
     *
     * @author: Tapas Jena
     * @copyright: Anitech Consulting Services Pvt Ltd.
     */
    angular.module('johnhancock', ['ui.bootstrap','ui.utils', 'ui.router', 'ngAnimate', 'restangular',
        'angular-loading-bar', 'home', 'help', 'common', 'post', 'disclosures', 'settings' ]);

    angular.module('johnhancock').config(function($stateProvider, $urlRouterProvider) {

        /* Add New States Above */
        $urlRouterProvider.otherwise('/home');

    });

    angular.module('johnhancock').run(function($rootScope) {

        $rootScope.safeApply = function(fn) {
            var phase = $rootScope.$$phase;
            if (phase === '$apply' || phase === '$digest') {
                if (fn && (typeof(fn) === 'function')) {
                    fn();
                }
            } else {
                this.$apply(fn);
            }
        };

    });

})();
