name: Test Jekyll site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        bundle install
        npm install

    - name: Build site
      run: bundle exec jekyll build

    - name: Run tests
      run: |
        bundle exec rake test
        npm run test:unit
        npm run test:links

    - name: Run E2E tests
      uses: cypress-io/github-action@v5
      with:
        start: bundle exec jekyll serve
        wait-on: 'http://localhost:4000'
        config: baseUrl=http://localhost:4000
